Fix OpenTofu issue
Removed `PGCHANNELBINDING=require`. It was causing the following error
message on OpenTofu commands:

  Error: pq: environment variable $PGCHANNELBINDING is not supported